"""Restructure SEC Code V4 to 3-level format

Revision ID: 003
Revises: 002
Create Date: 2026-02-11

Changes:
- sec_codes_v4: Drop discipline/spec_code columns, resize code to String(15)
- master_work_items: Add discipline, location, material_type, worker_grade, equip_type
- master_work_items: Resize sec_code_v4 to String(15), instance_code to String(20)
- activity_bom: Resize activity_code, resource_code to String(15)
- line_items: Resize sec_code_v4 to String(15)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ================================================================
    # 1. Add new attribute columns to master_work_items
    # ================================================================
    op.add_column('master_work_items', sa.Column(
        'discipline', sa.String(5), nullable=True,
        comment='Discipline: CV, AR, EL, PL, ME, FP',
    ))
    op.add_column('master_work_items', sa.Column(
        'location', sa.String(5), nullable=True,
        comment='Location (Activity): COL, BEM, SLB, FND, WAL',
    ))
    op.add_column('master_work_items', sa.Column(
        'material_type', sa.String(10), nullable=True,
        comment='Material type (Material): RDMX, HDPE, XLPE',
    ))
    op.add_column('master_work_items', sa.Column(
        'worker_grade', sa.String(10), nullable=True,
        comment='Worker grade (Labour): THO3, THO4, OPER',
    ))
    op.add_column('master_work_items', sa.Column(
        'equip_type', sa.String(10), nullable=True,
        comment='Equipment type (Equipment): PUMP, EXCV, CRAN',
    ))
    op.create_index('idx_master_discipline', 'master_work_items', ['discipline'])

    # ================================================================
    # 2. Extract discipline from old 5-level codes into new column
    #    e.g. A.CV.CON.POUR.COL → discipline='CV'
    # ================================================================
    op.execute("""
        UPDATE master_work_items
        SET discipline = SUBSTRING_INDEX(SUBSTRING_INDEX(sec_code_v4, '.', 2), '.', -1)
        WHERE sec_code_v4 IS NOT NULL
          AND discipline IS NULL
          AND LENGTH(sec_code_v4) - LENGTH(REPLACE(sec_code_v4, '.', '')) >= 4
    """)

    # ================================================================
    # 3. Extract location from old 5-level codes into new column
    #    e.g. A.CV.CON.POUR.COL → location='COL'
    # ================================================================
    op.execute("""
        UPDATE master_work_items
        SET location = SUBSTRING_INDEX(sec_code_v4, '.', -1)
        WHERE sec_code_v4 IS NOT NULL
          AND location IS NULL
          AND LENGTH(sec_code_v4) - LENGTH(REPLACE(sec_code_v4, '.', '')) >= 4
    """)

    # ================================================================
    # 4. Drop FK constraint on sec_code_v4 before modifying sec_codes_v4
    # ================================================================
    op.drop_constraint('fk_master_sec_code_v4', 'master_work_items', type_='foreignkey')

    # ================================================================
    # 5. Clear old 5-level data from sec_codes_v4 table
    #    (will be re-seeded with 3-level codes)
    # ================================================================
    op.execute("DELETE FROM activity_bom")
    op.execute("DELETE FROM sec_codes_v4")

    # ================================================================
    # 6. Modify sec_codes_v4 table: drop old columns, resize
    # ================================================================
    # Drop discipline and spec_code columns
    op.drop_index('idx_sec_v4_discipline', table_name='sec_codes_v4')
    op.drop_column('sec_codes_v4', 'discipline')
    op.drop_column('sec_codes_v4', 'spec_code')

    # Resize code column (PK) — requires dropping dependent FK first (done above)
    op.alter_column('sec_codes_v4', 'code',
                     existing_type=sa.String(30),
                     type_=sa.String(15))

    # ================================================================
    # 7. Resize master_work_items columns
    # ================================================================
    op.alter_column('master_work_items', 'sec_code_v4',
                     existing_type=sa.String(30),
                     type_=sa.String(15))
    op.alter_column('master_work_items', 'instance_code',
                     existing_type=sa.String(35),
                     type_=sa.String(20))

    # Clear old 5-level v4 codes from master items
    # (they'll be re-generated by the migration script)
    op.execute("""
        UPDATE master_work_items
        SET sec_code_v4 = NULL, instance_code = NULL
        WHERE sec_code_v4 IS NOT NULL
    """)

    # ================================================================
    # 8. Resize activity_bom columns
    # ================================================================
    op.alter_column('activity_bom', 'activity_code',
                     existing_type=sa.String(30),
                     type_=sa.String(15))
    op.alter_column('activity_bom', 'resource_code',
                     existing_type=sa.String(30),
                     type_=sa.String(15))

    # ================================================================
    # 9. Resize line_items.sec_code_v4
    # ================================================================
    op.alter_column('line_items', 'sec_code_v4',
                     existing_type=sa.String(30),
                     type_=sa.String(15))

    # ================================================================
    # 10. Re-create FK constraint
    # ================================================================
    op.create_foreign_key(
        'fk_master_sec_code_v4',
        'master_work_items', 'sec_codes_v4',
        ['sec_code_v4'], ['code'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    # Drop FK first
    op.drop_constraint('fk_master_sec_code_v4', 'master_work_items', type_='foreignkey')

    # Restore column sizes
    op.alter_column('line_items', 'sec_code_v4',
                     existing_type=sa.String(15),
                     type_=sa.String(30))
    op.alter_column('activity_bom', 'resource_code',
                     existing_type=sa.String(15),
                     type_=sa.String(30))
    op.alter_column('activity_bom', 'activity_code',
                     existing_type=sa.String(15),
                     type_=sa.String(30))
    op.alter_column('master_work_items', 'instance_code',
                     existing_type=sa.String(20),
                     type_=sa.String(35))
    op.alter_column('master_work_items', 'sec_code_v4',
                     existing_type=sa.String(15),
                     type_=sa.String(30))
    op.alter_column('sec_codes_v4', 'code',
                     existing_type=sa.String(15),
                     type_=sa.String(30))

    # Re-add discipline and spec_code columns
    op.add_column('sec_codes_v4', sa.Column('discipline', sa.String(5), nullable=True))
    op.add_column('sec_codes_v4', sa.Column('spec_code', sa.String(5), nullable=True))
    op.create_index('idx_sec_v4_discipline', 'sec_codes_v4', ['discipline'])

    # Re-create FK
    op.create_foreign_key(
        'fk_master_sec_code_v4',
        'master_work_items', 'sec_codes_v4',
        ['sec_code_v4'], ['code'],
        ondelete='SET NULL',
    )

    # Drop new columns
    op.drop_index('idx_master_discipline', table_name='master_work_items')
    op.drop_column('master_work_items', 'equip_type')
    op.drop_column('master_work_items', 'worker_grade')
    op.drop_column('master_work_items', 'material_type')
    op.drop_column('master_work_items', 'location')
    op.drop_column('master_work_items', 'discipline')
